### ISSUE TITLE
Missing ServerActionService Component from the package.

### ISSUE THREAD

**Issue by bricembouani** [pozil/platform-event-service#1]
Hi guys,
Thank you very much for this great component for Platform Event, which I'm using to handle events in Communities.
It seems that the component **ServerActionService** is missing from the package, it's used to handle the server-side call.
Could you please provide a sample of it?
Cheers.

**Comment by pozil** [comment]
HI @bricembouani. Thanks for the feedback and good catch on this missing component.
`ServerActionService` is a utility for performing server side calls. It's available as a package from here:
https://github.com/pozil/server-action-service

**Comment by bricembouani** [comment]
Great, thank you @pozil!
